### ISSUE TITLE
How I can use this library to decrypt the saved data?

### ISSUE THREAD

**Issue by KadamMangesh** [ophio/secure-preferences#17]
I want to securely save some sensitive data in shared pref. Later I need to decrypt the encrypted data and use in application. How I can achieve this using secure preferences library?

**Comment by vashisthg** [comment]
@MangeshKadam 
Please check the sample application. 

Create key by 

```
String key = KeyGenerator.get(KeystoreApplication.getAppContext(),
                    KeystoreApplication.getAppContext().getPackageName())
                        .loadOrGenerateKeys();
```

Obtain an instance of ObscuredSharedPreferences using ObscuredPreferencesBuilder as follows:

```

SharedPreferences sharedPreferences = new ObscuredPreferencesBuilder()
                .setApplication(KeystoreApplication.getAppContext())
                .obfuscateValue(true)
                .obfuscateKey(true)
                .setSharePrefFileName(PREFS_NAME)
                .setSecret(key)     //secret key we generated in step 1.
                .createSharedPrefs();
```

now use the instance of sharedPreferences created above to save/fetch data.

**Comment by vashisthg** [comment]
Hey @MangeshKadam Can we close this issue?

**Comment by KadamMangesh** [comment]
Hi thanks. you can close this issue.
