### ISSUE TITLE
Deprecated code after Android M

### ISSUE THREAD

**Issue by fcduarte** [ophio/secure-preferences#19]
Hi guys,

any plans to fix those deprecated methods?

KeyStoreKeyGenerator
- 'isBoundKeyAlgorithm(java.lang.String)' is deprecated

SecretKeyWrapper
- 'android.security.KeyPairGeneratorSpec' is deprecated
- 'android.security.KeyPairGeneratorSpec' is deprecated
- 'android.security.KeyPairGeneratorSpec.Builder' is deprecated

I'm just wondering what would be the best way to fix it.

Best,

**Comment by ragdroid** [comment]
For KeyStoreKeyGenerator, maybe we can do something like this below : 

```
boolean isHardwareSecured;
if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
    isHardwareSecured = KeyChain.isBoundKeyAlgorithm(algorithm);
} else {
    isHardwareSecured = keyInfo.isInsideSecureHardware();
}
```

More [info](http://developer.android.com/reference/android/security/KeyChain.html#isBoundKeyAlgorithm%28java.lang.String%29)

and something similar with [`KeyGenParameterSpec`](http://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.html)
cc @vashisthg @fcduarte

**Comment by ragdroid** [comment]
@vashisthg https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.html

This might help us.
