### ISSUE TITLE
Any further plans for improvement?

### ISSUE THREAD

**Issue by Rainer-Lang** [ophio/secure-preferences#5]
Maybe RxJava... https://github.com/pwittchen/prefser

**Comment by vashisthg** [comment]
Thanks for the suggestion. Wait for next iteration.

**Comment by Rainer-Lang** [comment]
OK thanks for the fast answer.
When do you want to release .02?

**Comment by vashisthg** [comment]
Let us discuss first about the usage of RxJava in our library and whether its an overkill for this project or not. 
@Rainer-Lang What are your suggestions for where RxJava could be useful here.

cc @ragdroid

**Comment by vashisthg** [comment]
As https://github.com/pwittchen/prefser wraps SharedPreferences, it could be used along with our library,  So I don't think we need to reinvent the wheel. @vickyturtle @ragdroid What are your thoughts?

**Comment by ragdroid** [comment]
@vashisthg Yes I agree. 
Also I am not sure where `RxJava` can be applied. Maybe @vickyturtle can give us a better idea regarding this.

**Comment by vickyturtle** [comment]
@vashisthg I don't think implementing RxJava in here makes much sense, but may be we can try to  make secure-preferences injectable in https://github.com/pwittchen/prefser in place of normal SharedPreferences.
