### ISSUE TITLE
Is it possible to make minSdk=14

### ISSUE THREAD

**Issue by trietbui85** [ophio/secure-preferences#8]
I know this lib is using some API from Android API 18.

> The Keystore system is used by the KeyChain API as well as the Android Keystore provider feature that was introduced in Android 4.3 (API level 18).

Therefore, the sample app has minSdkVersion=18. However, could you please decrease its minSdkVersion to 14, with a wrapper to use default SharedPreferences if device API version from 14 to 17, or use secure preferences if API >= 18?

**Comment by vashisthg** [comment]
I fear that it may cause some developers to accidentally use the library in lower versions thinking that share preferences are being encrypted. Developers could fork the repos and use it as they want.
